version: "3.2"
services:
  pwd:
    container_name: pwd
    image: golang
    command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null;
      cd /go/src/; go run api.go -save /pwd/sessions -name l2'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD:/go/src
    - sessions:/pwd
  l2:
    container_name: l2
    image: golang
    command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null;
      cd /go/src/router/l2; go run l2.go -ssh_key_path /etc/ssh/ssh_host_rsa_key -name
      l2 -save /pwd/networks'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD:/go/src
    - networks:/pwd
    ports:
    - "8022:22"
    - "8053:53"
    - "443:443"
volumes:
  sessions: null
  networks: null
